#!/usr/bin/env python

try:
    from wolis import runner
except ImportError:
    import os.path
    import sys
    
    sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..'))
    from wolis import runner

runner.Runner().run()
