#!/bin/sh

testroot=/var/www/func
passed=$testroot/.passed

set -e

continue=false
while getopts :c option; do
	case $option in
		c)
			continue=true;;
		*)
			echo "Usage: `basename $0` [-c]" 1>&2
			exit 10
			;;
	esac
done

if $continue && ! test -e $passed; then
	continue=false
fi

args=
if ! $continue; then
	args="$args --delete"
fi
rsync -a --exclude .git $args ~/apps/phpbb/phpBB/ $testroot/
chmod -R o+w $testroot || true

if ! $continue; then
	echo 'drop database if exists morpheus' |mysql -u root
	echo 'create database morpheus' |mysql -u root
fi

export PYTHONPATH=../owebunit:../ocookie

if ! $continue; then
	:>$passed
fi

try() {
	if $continue; then
		if fgrep -x "$1" $passed; then
			return
		fi
	fi
	run_test "$@"
	echo "$1" >>$passed
}

run_test() {
	#py.test "$@"
	python "$@"
}

try test/install.py
try test/login_without_cookies.py
try test/login.py
try test/acp_login.py
#try test/register.py

rm $passed
